refactored ec2ssh, moved ec2 instance listing code to ec2list, added easyaws command for quickstart, updated pip package config, and removing color echo (as it does not works on OSX)

diff --git a/easyaws/ec2ssh b/easyaws/ec2ssh
--- a/easyaws/ec2ssh
+++ b/easyaws/ec2ssh
@@ -1,100 +1,74 @@
 #!/bin/bash
-
-# Author: Amber Jain
-# Email: i.amber.jain {at} gmail
+#
+# FILE:        ec2ssh
+# DESCRIPTION: SSH into EC2 instances by public IP/DNS
+# AUTHOR:      Amber Jain
+# EMAIL:       i.amber.jain {at} gmail
 
 # TODO:
-# 1. Non-existing instance name supplied to -c
-# 2. Ability to specify username (-u option)
+# 1. Handle non-existing instance name supplied to -c
 
 set -e
 
 SELF_NAME=$(basename $0)
- 
-# Prints warning/error $MESSAGE in red foreground color
-red_echo() {
-    echo -e "\e[1;31m[E] $SELF_NAME: $MESSAGE\e[0m"
-}
-
-simple_red_echo() {
-    echo -e "\e[1;31m$MESSAGE\e[0m"
-}
-
-# Prints success/info $MESSAGE in green foreground color
-green_echo() {
-    echo -e "\e[1;32m[S] $SELF_NAME: $MESSAGE\e[0m"
-}
-
-simple_green_echo() {
-    echo -e "\e[1;32m$MESSAGE\e[0m"
-}
- 
-# Prints $MESSAGE in blue foreground color
-blue_echo() {
-    echo -e "\e[1;34m[I] $SELF_NAME: $MESSAGE\e[0m"
-}
-
-simple_blue_echo() {
-    echo -e "\e[1;34m$MESSAGE\e[0m"
-}
 
 help(){
-	echo "Usage: $0 [options] "
-	echo "Options:"
-	echo "  -h                 Print this help message"
-	echo "  -l                 List all EC2 instances (with instance state)"
-	echo "  -c <instance_name> Connect to specified ec2 instance name"
-	echo "  -i <identity_file> File from which the identity (private key) for public key authentication is read"
-	#echo "  -p <ssh_port>      Port to connect to on the remote host"
-	#echo "  -v                 Turn on verbose output for SSH command (when used with -c option)"
-	exit 0
+  cat<<EOF
+Usage:
+  $SELF_NAME [options]
+Options:
+  -h <host_ip_or_dns> EC2 host (Public/Elastic IP or public DNS of EC2 instance to connect with)
+  -i <identity_file>  File from which the identity (private key) for public key authentication is read
+  -l <login_name>     Specifies the username to log in as on the EC2 host
+  -p <ssh_port>       Port to connect to on the remote host
+  -v                  Turn on verbose output for SSH command
+EOF
+exit 0
 }
 
-list_instances(){
-	MESSAGE="Output format: (InstanceState, InstanceName, Keyname)" ; simple_blue_echo
-	aws ec2 describe-instances --query 'Reservations[].Instances[].[State.Name,Tags[?Key==`Name`] | [0].Value,KeyName]' --filters Name=instance-state-name,Values=running --output table
-	exit 0
-}
+# Print usage message if no arguments are given
+test $# -eq 0 && { help; }
 
-connect_ssh(){
-	MESSAGE="Trying to connect to EC2 instance: '$OPTARG'" ; blue_echo
-	INSTANCE_NAME=$OPTARG
-	INSTANCE_PUBLIC_DNS_NAME=`aws ec2 describe-instances --filters "Name=tag:Name,Values=$OPTARG" --query 'Reservations[].Instances[].[PublicDnsName]'`
-	INSTANCE_STATE=`aws ec2 describe-instances --filters "Name=tag:Name,Values=$OPTARG" --query 'Reservations[].Instances[].[State.Name]'`
-	if [[ $INSTANCE_STATE == "stopped" ]]
-	then
-  		MESSAGE="'$OPTARG' is NOT running" ; red_echo
-	else
-  		MESSAGE="Detected public DNS name of '$OPTARG' as '$INSTANCE_PUBLIC_DNS_NAME'" ; green_echo
-	fi
-}
-
-while getopts "hlc:i:" opt; do
+CMD="ssh"
+while getopts "h:i:l:p:v" opt; do
   case $opt in
     h)
-      help
-      ;;
+      EC2_HOST=$OPTARG ;;
+      #CMD="$CMD $OPTARG" ;;
+    i)
+      KEY_FILE_LOCATION=$OPTARG
+      CMD="$CMD -i $OPTARG" ;;
     l)
-	  list_instances
-	  ;;
-	i)
-	  KEY_FILE_LOCATION=$OPTARG
-	  ;;
-	c)
-	  connect_ssh
-	  ;;
+      SSH_USER=$OPTARG
+      CMD="$CMD -l $OPTARG" ;;
+    p)
+      SSH_PORT=$OPTARG
+      CMD="$CMD -p $OPTARG" ;;
+    v)
+      #SSH_VERBOSE="-vvv"
+      CMD="$CMD -vvv" ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      #echo "Invalid option: -$OPTARG" >&2
+      help
       exit 1
       ;;
   esac
 done
 
-if [ -z "$INSTANCE_PUBLIC_DNS_NAME" ]; then
-	help
-elif [ -z "$KEY_FILE_LOCATION" ]; then
-	help
+INSTANCE_STATE=`aws ec2 describe-instances --filters "Name=tag:Name,Values=$EC2_HOST" --query 'Reservations[].Instances[].[State.Name]'`
+
+if [[ $INSTANCE_STATE == "stopped" ]] ; then
+  echo "'$EC2_HOST' is NOT running. If you want to connect, ask your superadmin to boot this EC2 instance first."
+  exit 2
+elif [[ $INSTANCE_STATE == "running" ]]; then
+  echo "Trying to SSH into '$EC2_HOST'"
 else
-	MESSAGE="SSHing into '$INSTANCE_PUBLIC_DNS_NAME' (i.e. '$INSTANCE_NAME') with key '$KEY_FILE_LOCATION'" ; blue_echo
-	ssh ubuntu@$INSTANCE_PUBLIC_DNS_NAME -i $KEY_FILE_LOCATION
+  echo "'$EC2_HOST' does NOT exists. Please check output of 'ec2list' to see running EC2 instances."
+  exit 3
+  #MESSAGE="Detected public DNS name of '$OPTARG' as '$INSTANCE_PUBLIC_DNS_NAME'" ; green_echo
 fi
+
+INSTANCE_PUBLIC_DNS_NAME=`aws ec2 describe-instances --filters "Name=tag:Name,Values=$EC2_HOST" --query 'Reservations[].Instances[].[PublicDnsName]'`
+CMD="$CMD $INSTANCE_PUBLIC_DNS_NAME"
+
+$CMD
